# Trivy Configuration File
# This file customizes Trivy security scanning behavior

# Database settings
db:
  # Skip database update for faster scans (useful in CI)
  skip-update: false
  # Custom database repository (optional)
  # repository: "ghcr.io/aquasecurity/trivy-db"

# Vulnerability settings
vulnerability:
  # Skip vulnerabilities with no fix available
  ignore-unfixed: true
  # Vulnerability severity levels to report
  severity:
    - CRITICAL
    - HIGH
    - MEDIUM
  # Custom vulnerability database (optional)
  # type: "db"

# Secret scanning settings
secret:
  # Skip secret scanning for now (can be enabled later)
  skip-dirs:
    - "node_modules"
    - ".git"
    - "dist"
    - "coverage"
    - ".nx"
  skip-files:
    - "*.log"
    - "*.lock"
    - "pnpm-lock.yaml"

# License scanning settings
license:
  # Skip license scanning by default (handled separately)
  skip: true
  # Forbidden license types (can be customized)
  forbidden:
    - "GPL-2.0"
    - "GPL-3.0"
    - "AGPL-1.0"
    - "AGPL-3.0"

# Misconfiguration scanning settings
misconfig:
  # Scan for infrastructure misconfigurations
  skip: false
  # Include Dockerfile, Kubernetes, Terraform files
  include-non-failures: false
  severity:
    - CRITICAL
    - HIGH
    - MEDIUM

# Output settings
format: sarif
output: trivy-results.sarif

# Exit code settings
exit-code: 0  # Don't fail the build on vulnerabilities (handle in workflow)

# Performance settings
timeout: 15m
cache-backend: "fs"
cache-ttl: 24h

# Skip specific vulnerability IDs (use sparingly)
skip-policy-update: false
# ignore-policy: |
#   # Example: Skip specific CVEs with justification
#   # CVE-2021-44228:
#   #   reason: "False positive - not using log4j in production"
#   #   expiry: "2024-12-31"
