apiVersion: v1
kind: Namespace
metadata:
  name: enterprise-app
  labels:
    name: enterprise-app
    app.kubernetes.io/name: enterprise-app
    app.kubernetes.io/instance: enterprise-app
    app.kubernetes.io/version: "1.0.0"
---
# Resource Quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: enterprise-app-quota
  namespace: enterprise-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "4"
    pods: "20"
    services: "10"
    secrets: "5"
    configmaps: "10"
---
# Limit Range for pod resources
apiVersion: v1
kind: LimitRange
metadata:
  name: enterprise-app-limits
  namespace: enterprise-app
spec:
  limits:
  - type: Pod
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: "10m"
      memory: 16Mi
  - type: Container
    default:
      cpu: "100m"
      memory: 128Mi
    defaultRequest:
      cpu: "50m"
      memory: 64Mi
    max:
      cpu: "500m"
      memory: 512Mi
    min:
      cpu: "10m"
      memory: 16Mi
