apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-shared
  namespace: enterprise-app
  labels:
    app.kubernetes.io/name: enterprise-app
    app.kubernetes.io/component: config
data:
  # Configuration shared across multiple deployments
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://enterprise@postgres:5432/enterprise_db"
  REDIS_URL: "redis://redis:6379"
  KAFKA_BROKERS: "kafka:9092"
  LOG_LEVEL: "info"
  SESSION_TIMEOUT: "1800"
  CORS_ORIGIN: "*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastify-api-config
  namespace: enterprise-app
  labels:
    app.kubernetes.io/name: fastify-api
    app.kubernetes.io/component: config
data:
  # Fastify API specific configuration
  PORT: "3334"
  HOST: "0.0.0.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: enterprise-app
  labels:
    app.kubernetes.io/name: enterprise-app
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Secrets shared across multiple deployments
  # These are placeholder values - replace with actual base64-encoded secrets in production
  # Generate JWT_SECRET: openssl rand -hex 64 | base64
  # Generate POSTGRES_PASSWORD: echo "your-secure-password" | base64
  JWT_SECRET: "REPLACE_WITH_BASE64_ENCODED_JWT_SECRET"
  POSTGRES_PASSWORD: "REPLACE_WITH_BASE64_ENCODED_PASSWORD"
