# Pod Disruption Budget for Frontend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-app-pdb
  namespace: enterprise-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: web-app
---
# Pod Disruption Budget for Backend API
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fastify-api-pdb
  namespace: enterprise-app
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: fastify-api
---
# Horizontal Pod Autoscaler for API
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastify-api-hpa
  namespace: enterprise-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastify-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
