#!/bin/bash
# Environment Setup Script
# This script helps set up secure environment variables for local development

set -e

echo "🔧 Setting up secure environment variables..."

# Generate secure JWT secret
echo "📝 Generating secure JWT secret..."
JWT_SECRET=$(openssl rand -hex 64)

# Generate secure database password
echo "📝 Generating secure database password..."
DB_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)

# Create .env file
echo "📄 Creating .env file..."
cat > .env << EOF
# ⚠️  DEVELOPMENT ENVIRONMENT ONLY - DO NOT USE IN PRODUCTION ⚠️
# Generated by setup-env.sh on $(date)

# JWT Secret - Generated with: openssl rand -hex 64
JWT_SECRET=${JWT_SECRET}

# JWT Configuration
JWT_EXPIRES_IN=24h

# Database Configuration
POSTGRES_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://enterprise:\${POSTGRES_PASSWORD}@localhost:5432/enterprise_db

# Redis Configuration
REDIS_URL=redis://localhost:6379

# API Configuration
API_PORT=3333
NODE_ENV=development
LOG_LEVEL=info

# CORS Configuration (comma-separated)
CORS_ORIGINS=http://localhost:4200,http://localhost:4201

# Development flags
USE_LOCAL_SECRETS=true
SKIP_AWS_SECRETS=true
EOF

echo "✅ Environment setup complete!"
echo ""
echo "📋 Generated secrets:"
echo "   JWT_SECRET: ${JWT_SECRET:0:32}... (64 bytes)"
echo "   POSTGRES_PASSWORD: ${DB_PASSWORD}"
echo ""
echo "🔒 Security reminders:"
echo "   - Never commit .env to version control"
echo "   - Use different secrets for each environment"
echo "   - Rotate secrets regularly"
echo ""
echo "🚀 Next steps:"
echo "   1. Review the generated .env file"
echo "   2. Add GitHub repository secrets for CI/CD"
echo "   3. Set up AWS Secrets Manager for production"
echo ""
echo "ℹ️  The .env file has been created with secure random values."
